/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gr2td4;

/**
 *
 * @author yilunjiang
 */
public class IHMGarage extends javax.swing.JFrame {

    /**
     * Creates new form IHMGarage
     */
    public IHMGarage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonElectrique = new javax.swing.JRadioButton();
        jRadioButtonHybride = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Type de Vecule");

        jLabel2.setText("Renseignements");

        buttonGroup1.add(jRadioButtonElectrique);
        jRadioButtonElectrique.setText("Electrique");
        jRadioButtonElectrique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonElectriqueActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonHybride);
        jRadioButtonHybride.setText("Hybride");
        jRadioButtonHybride.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHybrideActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonHybride)
                            .addComponent(jRadioButtonElectrique))
                        .addGap(103, 103, 103)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(43, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(217, 217, 217))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonElectrique)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonHybride))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonElectriqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonElectriqueActionPerformed
        jTextArea1.setText("");
        for(int i=0; i<Tab.length; i++){
            if(Tab[i] instanceof Electrique){
                jTextArea1.append(Tab[i].getMarque() + "\t" + Tab[i].getModele() +"\t"+ Tab[i].getNbKmsEntreChaqueRevision());
                Electrique temp = (Electrique)Tab[i];
                jTextArea1.append(temp.getAutonomieMaax()+"\n");
            }
        }
    }//GEN-LAST:event_jRadioButtonElectriqueActionPerformed

    private void jRadioButtonHybrideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHybrideActionPerformed
       jTextArea1.setText("Marque\tModele\tRevision\tRecharcheable\t");
        for(int i=0; i<Tab.length; i++){
            if(Tab[i] instanceof Hybride){
                jTextArea1.append(Tab[i].getMarque() + "\t" + Tab[i].getModele() +"\t"+ Tab[i].getNbKmsEntreChaqueRevision()+"\n");
                Hybride temp = (Hybride)Tab[i];
                jTextArea1.append(temp.isRecharcheable()+"\n");
            }
        } 
    }//GEN-LAST:event_jRadioButtonHybrideActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IHMGarage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IHMGarage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IHMGarage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IHMGarage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IHMGarage().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButtonElectrique;
    private javax.swing.JRadioButton jRadioButtonHybride;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
private Voiture[]Tab;
    void setTableau(Voiture[]Tab){
        this.Tab = Tab;
    }
    
    void affichage(){
        for(int i=0; i<Tab.length; i++){
            jTextArea1.append(Tab[i].getMarque() + "\t" + Tab[i].getModele() +"\t"+ Tab[i].getNbKmsEntreChaqueRevision());
    }
    }
}

